### ISSUE TITLE
how to set path of the downloaded file?

### ISSUE THREAD

**Issue by programmermager** [inceptusp/fl_downloader#3]
Hi, first of all i wanna say thanks very much to created this lib which is so helpfull. But i wanna ask, is it possible to set custom path for the file. or check first if the file exist it just directly open it.

**Comment by mdpe-ir** [comment]
> Hi, first of all i wanna say thanks very much to created this lib which is so helpfull. But i wanna ask, is it possible to set custom path for the file. or check first if the file exist it just directly open it.


Hello @programmermager. 

I also had this problem and fix it with following steps : 

Just change :
 
`await FlDownloader.download("download url", fileName: "file name");`

to 

`await FlDownloader.download("download url", fileName: "FolderName/SubFolderName/file name");`

it will save your file in `Downloads/FolderName/SubFolderName/file name` :) 

PS : 
### Do not forget to create folder.
Ex :
 
```
String externalStorageDirPath = await AndroidPathProvider.downloadsPath;
Directory path = Directory(externalStorageDirPath + "/FolderName/SubFolderName"  );
path.create(recursive: true);


```

**Comment by inceptusp** [comment]
@programmermager first of all, thanks for the feedback... haha =)

By "is it possible to set custom path for the file" you mean other than the **Download** folder or a custom path inside the download folder as exemplified by @mdpe-ir?

Either way, the answers are:
1. Nope. By now we only offer the option to download to Download folder. We plan to offer options to download to custom paths but we are studying the best way to do this with the new restrictions to folder access imposed by Google.
2. the method showed by @mdpe-ir is the way to go if you mean "a custom path inside the download folder".
