### ISSUE TITLE
Question about download()

### ISSUE THREAD

**Issue by dv30fps** [inceptusp/fl_downloader#9]
What is the significance of the int returned by FlDownloader.download() ?
What values mean success and failure?

**Comment by dv30fps** [comment]
Never mind. When I call FlDownloader.download() in a loop, I found that the return value starts at 1 and increments with each successive call. It doesn't seem to signify success or failure.

**Comment by inceptusp** [comment]
@dv30fps the returned int is a downloadId so you can use this number to cancel a download that is running before it finishes or to open the downloaded file on Android only using this number

**Comment by inceptusp** [comment]
I will add this information on the method documentation

**Comment by dv30fps** [comment]
OK thanks. I decided to use another package that downloads the file to memory instead of writing it to storage. I need to do some processing on the contents before writing to storage. With fl_downloader, I need to read the downloaded file from storage, process, and write the processed contents to storage. The extra I/O operations with fl_downloader double the transit and processing time.
